/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData clean = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dishes = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fix = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData garden = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grocery = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laundry = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData organize = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData other = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pick_up = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meal = IconData(0xf0f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
